services:
  mysql_orders_container:
    image: mysql:8.0
    container_name: mysql_orders_container
    restart: always
    environment:
      MYSQL_DATABASE: db_orders
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3308:3308"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: java_orders_app
    depends_on:
      mysql_orders_container:
        condition: service_healthy
    ports:
      - "8082:8082"
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
