services:
  mysql_users_container:
    image: mysql:8.0
    container_name: mysql_users_container
    restart: always
    environment:
      MYSQL_DATABASE: 'db_user'
      MYSQL_USER: 'uniara'
      MYSQL_PASSWORD: 'uniara'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: java_users_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_users_container:3306/db_user?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: 'uniara'
      SPRING_DATASOURCE_PASSWORD: 'uniara'
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    depends_on:
      mysql_users_container:
        condition: service_healthy
    ports:
      - "8083:8083"
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
