services:
  mysql_payment_container:
    image: mysql:8.0
    container_name: mysql_payment_container
    restart: always
    environment:
      MYSQL_DATABASE: db_payment
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: java_payment_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_payment_container:3306/db_payment?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: 'root'
      SPRING_DATASOURCE_PASSWORD: '1234'
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    depends_on:
      mysql_payment_container:
        condition: service_healthy
    ports:
      - "8081:8081"
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
