services:
  mysql_products_container:
    image: mysql:8.0
    container_name: mysql_products_container
    restart: always
    environment:
      MYSQL_DATABASE: db_products
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: java_products_app
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mysql_users_container?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: 'root'
      SPRING_DATASOURCE_PASSWORD: '1234'
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    depends_on:
      mysql_products_container:
        condition: service_healthy

volumes:
  mysql_data:

networks:
  app-network:
